### PR TITLE
reapply Region refactor: xppm/yppm/xtp_u/ytp_v (#210)

### PR DESCRIPTION
**Pull request by rheacangeo**
reapply the reverted pr #210

### CODE REVIEW

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
we discussed closing this as a team. @oelbert we also discussed doing your changes in 2 steps, which do you prefer?

**Review by oelbert — APPROVED** [review]
Looks good! Excited to get this in Master

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Pull request merged**
