### PR TITLE
Merging stencils within d_sw.py : Take 2

### PR DESCRIPTION
**Pull request by gmao-ckung**
## Purpose

This PR looks to merge stencils within the `d_sw` routine in `d_sw.py` to potentially reduce the overhead of calling multiple stencils.  These changes were based on the stencil merges in #256 but applied to `d_sw.py` in #309.

## Code changes:

The following changes were made in `d_sw.py`
- `FloatField` replaces `utils.sd`
- `not_inlineq_pressure` and `vbke` stencils merged into `not_inlineq_pressure_and_vbke`
- `multiply` and `ubke` stencils  merged into `mult_ubke`
- `ke_from_behind`, `corners.fix_corner_ke`, and `horizontal_relative_vorticity_from_winds` merged into `ke_horizontal_vorticity`
- `ub_from_vort` and `vb_from_vort` merged into `ub_vb_from_vort`
- `zrat_vorticity` and `addition` merged into `zrat_vorticity`
- `u_from_ke` and `v_from_ke` merged into `u_and_v_from_ke`

The following changes were made in `corners.py`
- `fix_corners_ke` was removed
- `corner_ke` was turned into a gtscript function

The Voracity mean test was removed from `__init__.py`

The `ubke` and `vbke` test cases in `translate_d_sw.py` were modified since these respective stencils are now gtscript function calls, and stencils were created within `translate_d_sw.py` to tests these functions.

### CODE REVIEW

**Review by rheacangeo — APPROVED** [review]
Still looks great!

**Comment by rheacangeo** [comment]
Oh but, the numpy backend doesn't work ... something weird going on

**Comment by rheacangeo** [comment]
looks like testing ubke, vbke and vorticity volume mean are what is missing -- e.g. you may have just pulled over the changes to the d_sw file?

**Review by rheacangeo — CHANGES_REQUESTED** [review]
I accepted before I saw some of code hasn't been updated -- mostly the translate classes I think

**Comment by gmao-ckung** [comment]
Thanks for catching that!  I just updated the tests and verified at least on my end that the comprehensive tests pass on my desktop.

**Review by rheacangeo — APPROVED** [review]
Yay!

**Comment by rheacangeo** [comment]
Yay!!! I am so excited this passes, feel free to merge it!

**Pull request merged**
