### PR TITLE
Reapply pr238, 244 245, refactors to saturation adjustment and daint data directory change

### PR DESCRIPTION
**Pull request by rheacangeo**
## Purpose

Reapply PRs 238, 244 and 245

## Code changes:

Please see:
 - #238 
 - #245
 - #244

### CODE REVIEW

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Review by oelbert — APPROVED** [review]
nice

**Pull request merged**
