### PR TITLE
Changes to work with latest gt4py

### PR DESCRIPTION
**Pull request by jdahm**
## Purpose

Changes to public API in gt4py.

## Code changes:

- `gtscript._AxisOffset` -> `gtscript.AxisIndex`
- `AccessIntent` became an `enum.IntFlag`

## Infrastructure changes:

- Requires latest version of gt4py.

### CODE REVIEW

**Comment by eddie-c-davis** [comment]
launch jenkins

**Comment by eddie-c-davis** [comment]
launch jenkins

**Comment by eddie-c-davis** [comment]
launch jenkins

**Comment by eddie-c-davis** [comment]
launch jenkins

**Review by rheacangeo — APPROVED** [review]
Nice!!

**Comment by eddie-c-davis** [comment]
Thank you!

**Pull request merged**
