### PR TITLE
Rollback certain remapping_part1 changes

### PR DESCRIPTION
**Pull request by jdahm**
## Purpose

This portion of the remapping PR merged recently has strange incompatibility with a new gt4py develop branch build. This rolls back that failing part.

## Code changes:

- Adds back call to `copy_stencil` and `copy_j_adjacent` and rolls back `pn2_and_pk`.

### CODE REVIEW

**Review by eddie-c-davis — APPROVED** [review]
Looks good to me.

**Comment by jdahm** [comment]
This is being blocked by the issues in `daint_venv`. I have a PR open there to fix that.

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Comment by rheacangeo** [comment]
launch jenkins

**Pull request merged**
